### ISSUE TITLE
Typo in plotAngMom() subroutine

### ISSUE THREAD

**Issue by OriolAbril** [rjfarmer/mesaplot#1]
Calling subroutine plotAngMom() gives the error:
```    
>>> p.plotAngMom(m)  
Traceback (most recent call last):  
  File "<stdin>", line 1, in <module>  
  File "build/bdist.linux-x86_64/egg/mesaPlot/__init__.py", line 1912, in plotAngMom  
NameError: global name 'log' is not defined
```
It seems to be a typo in line 1912 of "mesaPlot/\_\_init\_\_.py" where there is a `xlog=log` instead of `xlog=xlog`.

**Comment by rjfarmer** [comment]
fixed, thanks
