### ISSUE TITLE
Plotting error 

### ISSUE THREAD

**Issue by kao25** [rjfarmer/mesaplot#16]
Dear Mr. Farmer:

I am trying to make a kipp plot from the python code you did. I am having trouble after compilation. 

Traceback (most recent call last):
  File "Abundances.py", line 5, in <module>
    p.plotKip3(m,show_mass_loc=True)
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1914, in plotKip3
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1025, in _addMixLabelsAxis
AttributeError: 'plot' object has no attribute 'mix_names'

Traceback (most recent call last):
  File "plotKip.py", line 14, in <module>
    p.plotKip(m,fig=fig,ax=ax,show=False)
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1877, in plotKip
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1914, in plotKip3
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1025, in _addMixLabelsAxis
AttributeError: 'plot' object has no attribute 'mix_names'
 

I don't know why ? i added this lines in history column list  

       mixing_regions 40
       burning_regions 40

        mx1_top
        mx1_bot
        mx2_top
        mx2_bot
        mixing_regions 20
        burning_regions 20
        mix_relr_regions 40

Thanks in advance for your help.
Kao

**Comment by rjfarmer** [comment]
Please provide the full set of python commands you are using. It would also help if you could put your history.data file online and provide a link to it.

Thanks

**Comment by kao25** [comment]
You will find the python code and history data.

https://www.dropbox.com/sh/hj6li81gl1yjfs9/AADT-rolUKnjXJCOoDbK4zjRa?dl=0


PS: i did not change the code it is exactly the same. I downloaded the zip
file from:  https://github.com/rjfarmer/mesaplot


Thanks

2018-07-03 16:50 GMT-04:00 Robert Farmer <notifications@github.com>:

**Comment by rjfarmer** [comment]
That is not *your* plot commands, thats my code. I don't need to see my code i need to see your code

**Comment by kao25** [comment]
I did write a code. I worked with yours. I used :
...../mesaplot/example/plotKipp.py

It works for me 3 months ago but not now.


If I understand well, I have to write my own code ?

**Comment by rjfarmer** [comment]
What i need to see is the commands you've typed into python, whether that is from one of the examples or from elsewhere. As you've not also specified the exact version of mesaPlot your using, telling me you've used an example doesn't help. 

> It works for me 3 months ago but not now.
It may also be the case the example needs updating, but i need to see what you have done first.

**Comment by kao25** [comment]
i typed this commands:

import mesaPlot as mp
m=mp.MESA()
p=mp.plot()
m.loadHistory()
p.plotKip3(m,xaxis='star_age',age_lookback=True,age_log=True)


Also this kippenhahn generic:


import mesaPlot as mp
m=mp.MESA()
p=mp.plot()
m.loadHistory()
p.plotKip3(m,show_mass_loc=True)


I tried to find the version of mesaplot but did not find it. i installed
mesaplot 3 months ago.


I'm sorry for this inconvenience !







2018-07-04 9:25 GMT-04:00 Robert Farmer <notifications@github.com>:

**Comment by rjfarmer** [comment]
Those lines with your history file work fine for me. You should try upgrading mesaplot to the newest version

**Comment by kao25** [comment]
Does mixing regions means :  mix_names  ?


Traceback (most recent call last):
  File "plotKip.py", line 14, in <module>
    p.plotKip(m,fig=fig,ax=ax,show=False)
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1877, in
plotKip
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1914, in
plotKip3
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1025, in
_addMixLabelsAxis
AttributeError: 'plot' object has no attribute 'mix_names'

I updated matplotlib and mesaplot and still have the same problem.

Thanks for your feedback. I will delete all python and re install it again,
maybe it will work.


2018-07-05 12:10 GMT-04:00 Robert Farmer <notifications@github.com>:
