### ISSUE TITLE
plotAbun xaxis error

### ISSUE THREAD

**Issue by OriolAbril** [rjfarmer/mesaplot#2]
I tried to plot abundance profiles using log(1-q) as the xaxis value using plotAbun() and I encountered an error. I then tried the same commands on the profile17.data found in the examples/ directory with the following result:
```
>>> import mesaPlot as mp
>>> m=mp.MESA()
>>> p=mp.plot()
>>> m.loadProfile(num=-1)
LOGS//profile17.data
>>> p.plotAbun(m,xaxis='logxq')
/usr/local/lib/python2.7/dist-packages/mesaPlot-0.0-py2.7.egg/mesaPlot/__init__.py:1287: RuntimeWarning: divide by zero encountered in log10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/mesaPlot/__init__.py", line 1455, in plotAbun
  File "build/bdist.linux-x86_64/egg/mesaPlot/__init__.py", line 1306, in _plotAnnotatedLine
  File "build/bdist.linux-x86_64/egg/mesaPlot/__init__.py", line 911, in _annotateLine
  File "/usr/lib/python2.7/dist-packages/scipy/interpolate/polyint.py", line 54, in __call__
    y = self._evaluate(x)
  File "/usr/lib/python2.7/dist-packages/scipy/interpolate/interpolate.py", line 448, in _evaluate
    out_of_bounds = self._check_bounds(x_new)
  File "/usr/lib/python2.7/dist-packages/scipy/interpolate/interpolate.py", line 475, in _check_bounds
    raise ValueError("A value in x_new is below the interpolation "
ValueError: A value in x_new is below the interpolation range.
```
I took a look at the code and I thought the problem would be because of the negative values in the x axis so I tried the following:
```
p.plotAbun(m,xaxis='logxq',xmin=0,xmax=-5)
```
Inverting the axis did not raise ValueError any longer but the result had no longer annotated lines:
![abun_logxq](https://cloud.githubusercontent.com/assets/23738400/23506841/88f5b1de-ff4a-11e6-9215-97ec239c0e38.png)
I changed the axis to [50,-150] too to check that they actually were not there and no only not visible.

**Comment by rjfarmer** [comment]
Can you give  65a6ad8 a try? I think i've fixed it

**Comment by OriolAbril** [comment]
Yes, thanks! Now the first set of commands works and gives the abundance profile with annotated line, however now setting an xmin larger than xmax raises an error:
```
Traceback (most recent call last):
  File "abundances.py", line 21, in <module>
    p.plotAbun(m,xmin=1.3,xmax=0)
  File "build/bdist.linux-x86_64/egg/mesaPlot/__init__.py", line 1466, in plotAbun
  File "build/bdist.linux-x86_64/egg/mesaPlot/__init__.py", line 1317, in _plotAnnotatedLine
  File "build/bdist.linux-x86_64/egg/mesaPlot/__init__.py", line 909, in _annotateLine
  File "/usr/local/lib/python2.7/dist-packages/numpy-1.12.0-py2.7-linux-x86_64.egg/numpy/lib/nanfunctions.py", line 237, in nanmin
    res = np.fmin.reduce(a, axis=axis, out=out, **kwargs)
ValueError: zero-size array to reduction operation fmin which has no identity
```
I does not have much importance though because the axis can be easily inverted by doing:
```
fig=plt.figure(figsize=(12,12))
ax=fig.add_subplot(111)
p.plotAbun(m,xaxis='logxq',fig=fig,ax=ax,xmin=-0.5,xmax=0,show=False)
ax.invert_xaxis()
plt.show()
```

**Comment by rjfarmer** [comment]
You can also pass xrev=True to the plotAbun to reverse the xaxis

**Comment by OriolAbril** [comment]
Great, thanks a lot.
